ID,Name,Sequence,C-MODIFICATION,N-MODIFICATION,LINEAR/CYCLIC,STEREOCHEMISTRY,MODIFIED-RESIDUE,FUNCTION,ACTIVITY,RBC_SOURCE,LENGTH
1002,D20-S4,ALWMTLLKKVLKAAAKAALDAVLVGANA,Free,Free,Linear,L,None,Antimicrobial,LC50 =1.2±0.1μM,Human,28
1003,D4-S4,ALWDTLLKKVLKAAAKAALNAVLVGANA,Free,Free,Linear,L,None,Antimicrobial,LC50 =2.3±0.3μM,Human,28
